accounts/urls.py
from django.urls import path , include
from . import views 

app_name='accounts'

 
urlpatterns = [
    path('signup',views.SignUp,name ='SignUp' ),
    path('profile',views.profile,name ='profile' ),
    path('profile_edit',views.profile_edit,name ='profile_edit' ),
 
]

job/urls.py
from django.urls import path  
from . import views 
from . import api

#.................
app_name = 'job'
urlpatterns = [
    path('',views.job_list,name ='job_list' ),
    path('add',views.add_job ,name= 'add_job'),
    path('<str:slug>',views.job_details ,name= 'job_detail'),
    ###apis
    path('api/list',api.joblistapi,name= 'joblistapi'),
    path('api/jobs/<int:id>',api.job_detail_api ,name= 'job_detail_api'),
    #class based View gen
    path('api/v2/jobs',api.JobListApi.as_view() ,name= 'JobListApi'),
    path('api/v2/jobs/<int:id>',api.JobDetail.as_view() ,name= 'JobDetail'),

]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [   
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('job/', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls', namespace='contact')),
    path('api-auth/', include('rest_framework.urls')), 

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #city = models.
    phone_num=models.CharField(max_length=11,null=True ,blank=True)
    image= models.ImageField(upload_to ='profile/')
    
    def __str__(self):
        return str(self.user)


@receiver(post_save ,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . models import Profile

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model =Profile
        fields = ['phone_num','image']

accounts/views.py
from importlib.machinery import FrozenImporter
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate ,login
from django.urls import reverse

from accounts.models import Profile

from .forms import SignUpForm,ProfileForm,UserForm

# Create your views here.
def SignUp(request):
    if request.method =='POST':
         
        form =SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password= form.cleaned_data.get('password1')
            user = authenticate(username =username,password = password) 
            login(request,user) 

            return redirect('/accounts/profile')

    else :
        form =SignUpForm()   
              
             
    return render (request,'registration/signup.html',{'form':form})
    





def profile(request):
    profile= Profile.objects.get(user=request.user)
    return render(request  ,'accounts/profile.html',{'profile':profile})

def profile_edit(request):
    profile =  Profile.objects.get(user=request.user)   
    if request.method =='POST':
        userform =UserForm(request.POST,instance=request.user)
        profileform= ProfileForm(request.POST,request.FILES,instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile= profileform.save(commit=False)
            myprofile.user= request.user
            myprofile.save()
            return redirect(reverse('accounts:profile'))   
    else:
        userform =UserForm(instance=request.user)
        profileform= ProfileForm(instance=profile)


    return render(request,'accounts/profile_edit.html',{'userform':userform,'profileform':profileform })

accounts/templates/accounts/profile.html
{% extends "base_generic.html" %} 
 
{% block content %}

                 <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name : <span>{{ profile}}</span></li>
                                <li>Email: <span>{{ profile.user.email}}</span></li>
                                <li>Phone: <span> {{profile.phone_num }} </span></li>
                              </ul>
                            </div>
                                
                            <div  class = "p-5" >
                        <a  href="{% url 'accounts:profile_edit' %} "   class="boxed-btn3 w-50" type="submit">Edit Profile</a>
                         
                            </div>
                    </div>
           
           
                </div>

  
{% endblock %}

accounts/templates/accounts/profile_edit.html
 {% extends 'base.html' %}
 {% load bootstrap4 %}
    {% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
          
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                             
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{jobd}}</h4></a>
                              
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
               
                    <div class="apply_job_form white-bg">
                        <h4>Edit profile</h4>
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form  userform %}
                            {% bootstrap_form  profileform %}
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Edit Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
 
            </div>
        </div>
    </div>
    {% endblock body %}

     